Repository ScanDaLouS47/devathon-frontend, pull requests merged in 2024-08, with the labels that each got.

#11 Feature/user manipulation
  interfaces/respRegister.ts
  src/auth/context/AuthProvider.tsx
  src/auth/context/authReducer.ts
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/register/RegisterPage.tsx
  src/data/options.ts
  src/interfaces/index.ts
  src/interfaces/respFetch.ts
  src/routes/PublicRoutes.tsx
  src/utils/fetchApi.ts
  tsconfig.app.json
Labels: bug

#12 refactor: update fetch and uncomment route
  src/routes/PrivateRoutes.tsx
  src/routes/PublicRoutes.tsx
  src/utils/fetchApi.ts
Labels: bug

#15 Feature/styles
  src/App.scss
  src/App.tsx
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/login/loginPage.scss
  src/auth/pages/register/registerPage.scss
  src/auth/pages/updatePassword/updatePassPage.scss
  src/components/header/Header.tsx
  src/components/header/header.module.scss
  src/components/icons/LogoV2.tsx
  src/components/icons/UserIconV2.tsx
  src/main.tsx
  src/panel/components/Aside.tsx
  src/panel/components/aside.scss
  src/panel/pages/adminPanel/DashboardPage.tsx
  src/panel/pages/userPanel/userPage/userPage.module.scss
  src/routes/AppRouter.tsx
  src/routes/PrivateRoutes.tsx
  src/routes/PrivateUserRoutes.tsx
  src/routes/PublicRoutes.tsx
  src/scss/reset/_reset.scss
  src/scss/variables/_variables.scss
  src/utils/fetchApi.ts
Labels: enhancement

#16 Feature/styles
  package.json
  src/App.scss
  src/assets/font/Poppins-Bold.woff
  src/assets/font/Poppins-Regular.woff
  src/assets/font/Poppins-SemiBold.woff
  src/assets/google.svg
  src/assets/logo_tabletact.png
  src/assets/table_tact_logo_nobg.svg
  src/assets/tabletact_logo.png
  src/auth/pages/forgot/forgotPassPage.scss
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/login/loginPage.scss
  src/auth/pages/register/registerPage.scss
  src/auth/pages/updatePassword/updatePassPage.scss
  src/components/formInput/FormInput.tsx
  src/components/formInput/formInput.scss
  src/components/formInputPhone/FormInputPhone.tsx
  src/components/formInputPhone/formInputPhone.module.scss
  src/components/header/Header.tsx
  src/components/header/header.module.scss
  src/components/icons/GoogleIcon.tsx
  src/components/icons/HidePassword.tsx
  src/components/icons/LogOutIcon.tsx
  src/components/icons/Logo.tsx
  src/components/icons/SettingsIcon.tsx
  src/components/icons/ShowPassword.tsx
  src/components/icons/UserIcon.tsx
  src/components/icons/XIcon.tsx
  src/interfaces/link.interface.ts
  src/panel/components/Aside.tsx
  src/panel/components/aside.scss
  src/panel/components/eventContent/EventContent.tsx
  src/panel/components/eventContent/eventContent.scss
  src/panel/pages/userPanel/schedulesPage/SchedulesPage.tsx
  src/panel/pages/userPanel/schedulesPage/schedulesPage.scss
  src/routes/PrivateRoutes.tsx
  src/routes/PrivateUserRoutes.tsx
  src/scss/reset/_reset.scss
Labels: enhancement

#19 Feature/styles
  src/auth/pages/login/loginPage.scss
  src/components/formInputPhone/FormInputPhone.tsx
  src/components/formInputPhone/formInputPhone.module.scss
  src/components/header/Header.tsx
  src/components/header/header.module.scss
  src/components/icons/ThemeDark.tsx
  src/components/icons/ThemeLight.tsx
  src/components/themeSwitcher/ThemeSwitcher.tsx
  src/components/themeSwitcher/themeSwitcher.module.scss
  src/panel/components/aside.scss
  src/scss/reset/_reset.scss
Labels: duplicate

#20 Feature/refactor fetch
  src/auth/pages/login/LoginPage.tsx
  src/utils/apiError.ts
  src/utils/fetchApiV2.ts
  src/utils/getCookie.ts
Labels: enhancement

#21 Revert "Feature/refactor fetch"
  src/auth/pages/login/LoginPage.tsx
  src/utils/apiError.ts
  src/utils/fetchApiV2.ts
  src/utils/getCookie.ts
Labels: bug

#26 Chore/settings
  src/assets/table_tact_without_bg.png
  src/assets/table_tact_without_bg.svg
  src/auth/pages/login/loginPage.scss
  src/components/formInput/FormInput.tsx
  src/components/formInputImgFile/FormInputFileImgPreview.tsx
  src/components/formInputImgFile/formInputImgPreview.module.scss
  src/panel/pages/accountSettings/settings/Settings.tsx
Labels: documentation

#27 Feature/my reservations
  src/auth/context/AuthContext.ts
  src/auth/context/AuthProvider.tsx
  src/auth/context/authReducer.ts
  src/auth/pages/forgot/ForgotPassPage.tsx
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/register/RegisterPage.tsx
  src/auth/pages/updatePassword/UpdatePassPage.tsx
  src/components/formInput/FormInput.tsx
  src/components/formInputImgFile/FormInputFileImgPreview.tsx
  src/components/header/Header.tsx
  src/interfaces/index.ts
  src/interfaces/respBooking.interface.ts
  src/interfaces/respFetch.ts
  src/interfaces/respForAdmin.interface.ts
  src/interfaces/respForUser.interface.ts
  src/interfaces/respLogin.interface.ts
  src/interfaces/respLogout.interface.ts
  src/interfaces/user.interface.ts
  src/panel/pages/accountSettings/changePassword/ChangePassword.tsx
  src/panel/pages/accountSettings/didForgetPassword/DidForgetPass.tsx
  src/panel/pages/accountSettings/settings/Settings.tsx
  src/panel/pages/accountSettings/settings/settingsSchema.ts
  src/panel/pages/userPanel/myReservations/MyReservations.tsx
  src/panel/pages/userPanel/myReservations/myReservations.module.scss
  src/utils/User.ts
  src/utils/XsrfCookie.ts
  src/utils/fetchApi.ts
  src/utils/fetchApiV2.ts
Labels: enhancement

#28 Feature/my reservations
  .env.example
  src/auth/pages/forgot/ForgotPassPage.tsx
  src/auth/pages/forgot/forgotPassPage.module.scss
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/login/loginPage.module.scss
  src/auth/pages/register/RegisterPage.tsx
  src/auth/pages/register/registerPage.module.scss
  src/auth/pages/updatePassword/UpdatePassPage.tsx
  src/auth/pages/updatePassword/updatePassPage.module.scss
  src/components/formInput/FormInput.tsx
  src/components/formInput/formInput.module.scss
  src/components/header/Header.tsx
  src/components/pagination/Pagination.tsx
  src/components/pagination/pagination.module.scss
  src/interfaces/index.ts
  src/interfaces/respBooking.interface.ts
  src/interfaces/respDetailsForCalendar.interface.ts
  src/interfaces/respForAdmin.interface.ts
  src/interfaces/user.interface.ts
  src/panel/pages/accountSettings/changePassword/ChangePassword.tsx
  src/panel/pages/accountSettings/changePassword/changePassword.module.scss
  src/panel/pages/accountSettings/didForgetPassword/DidForgetPass.tsx
  src/panel/pages/accountSettings/didForgetPassword/didForgetPass.module.scss
  src/panel/pages/accountSettings/settings/Settings.tsx
  src/panel/pages/userPanel/myReservations/MyReservations.tsx
  src/panel/pages/userPanel/myReservations/myReservations.module.scss
  src/panel/pages/userPanel/myReservations/myReservationsSchema.ts
  src/panel/pages/userPanel/schedulesPage/schedulesPage.scss
Labels: enhancement

#30 Feature/reservation
  public/images/dish_1.webp
  public/images/dish_2.webp
  public/images/dish_base.webp
  src/App.scss
  src/auth/routes/AuthRoutes.tsx
  src/components/checkBox/CheckBox.tsx
  src/landing/LandingPage.tsx
  src/landing/landingPage.module.scss
  src/panel/components/icons/index.ts
  src/panel/hooks/useBooking.ts
  src/panel/pages/userPanel/booking/BookingPage.tsx
  src/panel/pages/userPanel/booking/bookingPage.scss
  src/panel/pages/userPanel/schedulesPage/schedulesPage.scss
  src/routes/AppRouter.tsx
Labels: enhancement

#32 Feature/refactor/styles
  package.json
  src/App.scss
  src/app/store.ts
  src/auth/pages/forgot/forgotPassPage.module.scss
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/login/loginPage.module.scss
  src/auth/pages/register/registerPage.module.scss
  src/auth/pages/updatePassword/updatePassPage.module.scss
  src/components/header/Header.tsx
  src/components/header/header.module.scss
  src/components/icons/EditingIcon.tsx
  src/components/icons/UploadIcon.tsx
  src/components/pagination/Pagination.tsx
  src/components/pagination/pagination.module.scss
  src/components/select/select.scss
  src/features/bookins/bookinsThunk.ts
  src/features/myBookings/myBookingsSlice.ts
  src/features/myBookings/myBookingsThunks.ts
  src/panel/components/Aside.tsx
  src/panel/components/icons/ArrowRightIcon.tsx
  src/panel/components/icons/TrashIcon.tsx
  src/panel/components/pagination/Pagination.tsx
  src/panel/components/pagination/giveEmptyRows/GenerateEmptyRows.tsx
  src/panel/components/pagination/giveEmptyRows/generateEmptyRows.module.scss
  src/panel/components/pagination/pagination.module.scss
  src/panel/pages/accountSettings/changePassword/ChangePassword.tsx
  src/panel/pages/accountSettings/changePassword/changePassword.module.scss
  src/panel/pages/accountSettings/didForgetPassword/DidForgetPass.tsx
  src/panel/pages/accountSettings/didForgetPassword/didForgetPass.module.scss
  src/panel/pages/accountSettings/settings/settings.module.scss
  src/panel/pages/userPanel/booking/bookingPage.scss
  src/panel/pages/userPanel/myReservations/MyReservations.tsx
  src/panel/pages/userPanel/myReservations/myReservations.module.scss
  src/panel/pages/userPanel/schedulesPage/schedulesPage.scss
  src/scss/reset/_reset.scss
  src/utils/fetchApi.ts
Labels: enhancement

#33 Feature/tests
  README.md
  src/App.tsx
  src/auth/context/AuthProvider.tsx
  src/auth/pages/index.ts
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/login/loginPage.module.scss
  src/auth/pages/register/RegisterPage.tsx
  src/components/header/Header.tsx
  src/components/themeSwitcher/themeSwitcher.module.scss
  src/features/bookins/bookinsThunk.ts
  src/features/myBookings/myBookingsThunks.ts
  src/interfaces/index.ts
  src/interfaces/respForUser.interface.ts
  src/panel/components/aside.module.scss
  src/panel/components/pagination/Pagination.tsx
  src/panel/components/pagination/btnPagesToShow/BtnPagesToShow.tsx
  src/panel/components/pagination/btnPagesToShow/btnPagesToShow.module.scss
  src/panel/components/pagination/giveEmptyRows/GenerateEmptyRows.tsx
  src/panel/components/pagination/giveEmptyRows/generateEmptyRows.module.scss
  src/panel/components/pagination/pagination.module.scss
  src/panel/pages/accountSettings/changePassword/changePassword.module.scss
  src/panel/pages/accountSettings/didForgetPassword/didForgetPass.module.scss
  src/panel/pages/accountSettings/settings/Settings.tsx
  src/panel/pages/accountSettings/settings/settings.module.scss
  src/panel/pages/userPanel/myReservations/MyReservations.tsx
  src/panel/pages/userPanel/myReservations/myReservations.module.scss
  src/panel/pages/userPanel/myReservations/myReservationsSchema.ts
  src/scss/functions/_functions.scss
  src/scss/reset/_reset.scss
  src/utils/fetchApi.ts
  src/utils/fetchApiV2.ts
  toDo.md
Labels: enhancement

#34 Feature/reservation
  src/auth/pages/login/LoginPage.tsx
  src/components/select/select.scss
  src/features/bookins/bookinsThunk.ts
  src/interfaces/respFetch.ts
  src/panel/components/calendarInfo/CalendarInfo.tsx
  src/panel/components/calendarInfo/calendarInfo.module.scss
  src/panel/components/eventContent/eventContent.scss
  src/panel/hooks/useSchedulesForm.ts
  src/panel/pages/userPanel/booking/BookingPage.tsx
  src/panel/pages/userPanel/booking/bookingSchema.ts
  src/panel/pages/userPanel/schedulesPage/SchedulesPage.tsx
  src/panel/pages/userPanel/schedulesPage/schedulesPage.scss
  src/utils/fetchApiV2.ts
Labels: enhancement

#35 Feature/test bis
  src/features/myBookings/myBookingsThunks.ts
  src/panel/pages/userPanel/myReservations/MyReservations.tsx
  src/panel/pages/userPanel/myReservations/myReservationsSchema.ts
  src/utils/fetchApi.ts
  toDo.md
Labels: enhancement
