Repository ScanDaLouS47/devathon-frontend, pull requests merged in 2024-07, with the labels that each got.

#1 add: pull_request_template template
  .eslintrc.cjs
  .gitignore
  .prettierrc
  README.md
  index.html
  package.json
  public/vite.svg
  pull_request_template.md
  src/App.scss
  src/App.tsx
  src/app/store.ts
  src/assets/react.svg
  src/index.scss
  src/main.tsx
  src/scss/reset/_reset.scss
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: documentation

#3 Feature/routes
  src/App.tsx
  src/auth/pages/LoginPage.tsx
  src/auth/pages/RegisterPage.tsx
  src/auth/pages/index.ts
  src/auth/routes/AuthRoutes.tsx
  src/components/icons/WarningIcon.tsx
  src/main.tsx
  src/panel/components/Aside.tsx
  src/panel/pages/adminPanel/AdminPage.tsx
  src/panel/pages/adminPanel/DashboardPage.tsx
  src/panel/pages/adminPanel/ListReservationsPage.tsx
  src/panel/pages/adminPanel/ReservationsPage.tsx
  src/panel/pages/userPanel/MyReservations.tsx
  src/panel/pages/userPanel/SchedulesPage.tsx
  src/panel/pages/userPanel/UserPage.tsx
  src/panel/routes/AdminRoutes.tsx
  src/routes/AppRouter.tsx
  src/routes/PrivateRoutes.tsx
  src/routes/PublicRoutes.tsx
Labels: enhancement

#4 Feature/login
  src/App.scss
  src/auth/pages/LoginPage.tsx
  src/auth/pages/index.ts
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/login/loginPage.scss
  src/auth/pages/login/losginSchema.ts
  src/components/formInput/FormInput.tsx
  src/components/formInput/formInput.scss
  src/scss/reset/_reset.scss
Labels: enhancement

#5 feat: create register form and validations
  .gitignore
  src/auth/pages/RegisterPage.tsx
  src/auth/pages/index.ts
  src/auth/pages/login/LoginPage.tsx
  src/auth/pages/register/RegisterPage.tsx
  src/auth/pages/register/registerPage.scss
  src/auth/pages/register/registerSchema.ts
Labels: enhancement

#7 Feature/register
  .env.example
  .github/PULL_REQUEST_TEMPLATE/template.md
  .github/pull_request_template.md
  public/options.ts
  src/auth/pages/login/loginPage.scss
  src/auth/pages/register/RegisterPage.tsx
  src/auth/pages/register/registerPage.scss
  src/auth/pages/register/registerSchema.ts
  src/components/formInput/FormInput.tsx
  src/components/formInput/formInput.scss
  src/components/formSelect/FormInputPhone.tsx
  src/components/formSelect/formInputPhone.module.scss
  src/components/icons/HidePassword.tsx
  src/components/icons/ShowPassword.tsx
  src/scss/reset/_reset.scss
  src/utils/fetchApi.ts
  tsconfig.app.json
Labels: documentation, enhancement

#8 Feature/auth
  src/auth/context/AuthContext.ts
  src/auth/context/AuthProvide.tsx
  src/auth/context/authReducer.ts
  src/auth/hook/useAuth.ts
Labels: enhancement

#9 Feature/register
  .env.example
  src/auth/pages/register/RegisterPage.tsx
  src/components/formSelect/FormInputPhone.tsx
  src/components/formSelect/formInputPhone.module.scss
  src/supabase/Client.ts
Labels: documentation, enhancement
